# Generated by Django 5.2 on 2025-04-20 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solveclimate.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solveclimate.team')),
            ],
        ),
        migrations.CreateModel(
            name='Basic_User_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solveclimate.user')),
            ],
        ),
    ]
